"""empty message

Revision ID: c867ce96cb45
Revises: 03265347249a
Create Date: 2020-11-03 13:06:02.769575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c867ce96cb45"
down_revision = "03265347249a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("email", sa.String(length=64), nullable=True),
        sa.Column("password", sa.String(length=512), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
